using BreakerServer.Configuration;
using BreakerServer.Services;
using Microsoft.Extensions.Options;

namespace BreakerServer.Endpoints;

public static class NewsEndpoints
{
    private static readonly byte[] FallbackNewsImage = Convert.FromBase64String(
        "iVBORw0KGgoAAAANSUhEUgAABAAAAAIACAYAAAAczR65AAAUaUlEQVR42u3dXWiWhf/H8c/WHqjUUCSMOuig7EEsD6qlhWEk2klh5TBxoKHQg6VYiomFg7QkFLUkwdgqjR7UmYpTs5Vpag+OxGrSSooOfgQFopLo7J7/g+j+N90sK/tVv9fr6Oa67ut7PWwge9/XdVvyn+U5HgAAAOBfrdQlAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAABAAAAAAAD+VUp69ep13GUAAACAfzd3AAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAKASwAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAMDf1xdffJEVK1Zk5cqV2bhxY4YOHfqHZ7a0tJyxY9ywYUOuv/7609q+b9++qamp+dudFwDQUZlLAABnzrFjxzJy5MgkyZVXXpm6urps3rz5b3uMl19+eZ555pnTChWtra1pbW31wwaAvzl3AADAX2Tv3r0pFApJfvq0e/78+bnnnnty3nnnZdGiRXnllVeyatWqDBgwIMlPn6w3NDSkqakpEyZMOGle7969s3nz5vTt27fLGSfua9y4cdm4cWM2bNiQwYMHnzTz888/T58+fbqct2nTpvTp0ydJUlFRka1bt6a0tLT46X1n63v27NnprN69e6euri4NDQ2ZP3++XxAAOMPcAQAAf5Ebbrghs2bNKv5xvGbNmrz77rt5+umnU19fn48//jgXXnhh6urqMmzYsIwdOzZPPfVUWltb09TUlKVLlxZnlZeXZ/HixZk1a1ZaW1u7nHHivnbv3p0bb7wxffr0ycSJE7N169YOxzh48OBs3749M2fO7HTe+vXrM3To0CxbtiyDBg3Kli1b0t7eXty+s/UzZszodNZjjz2WdevWZfXq1Rk2bFhuv/12vyQAIAAAwD9TeXl5VqxYkYqKilx99dXZsWNHNm/enEKhkG3btiVJbrrpplx88cXFbc4555ycddZZmTNnTm677bbccsst6datW4e5s2fPzurVq7N9+/ZTzigUCh329fbbb2fBggV58cUXM3ny5A7HWFZWlksuuSQ333xz1q9f3+m89evXp7a2NsuWLcvQoUPzxhtvdDiuztYvXry401kDBw7M1KlTkyRNTU3FuyMAAAEAAP5xTny+vqGhIUlSKBSKn5yXlZVlzJgxOXr0aEpLS3PttdemUChkyZIlaWxsTH19fYcv2auoqMhll12WJHn11VdPOePEfU2ZMiVVVVUZP358RowYkSlTpnQ4xvvuuy/V1dVdztu3b1969uyZbt26pV+/fpk5c2aH8+1sfVezysvLi9uVlJSkpKTELwwAnEG+AwAA/iL79+/P119/fdLyjz76KMOHD0+SDBkyJBMnTkySXHXVVVm3bl0qKytTWVlZfH9bW1tGjBiRiy66KKNHjz7ljF/q3r17Vq5cmebm5kyaNClDhgw56T3btm3LgAEDTjlv06ZNeeCBB7J79+4cP378pBknru9qVnNzc/ExheHDhwsAAHCGuQMAAM6gn2+v//kT+OnTp5/0ntra2sydOzc1NTX58ccfM23atCTJSy+9lDVr1qSlpSUHDhxIRUVF2trakiTt7e158MEHs3bt2rS0tHQ545cOHTqUt956K2vXrk1paWkWLlx40nv27duXK664IqNGjcqTTz7Z6bz169dn8+bNqa6u7vScT1zf1bHV1tZmwYIFGTt2bHbt2lU8NwDgzCjp1avXcZcBAAAA/t08AgAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAgAAAAAAACAAAwGm45JJLcv/996d79+4dXgMACAAA8A9TXV2dxsbGrFmzJo2NjRk5cmRx3dKlS3PkyJEUCoUOr1taWpIkffv2TU1NzZ9yHF9++WVef/31Dst+3s+ZcCZnAwB/rjKXAAD+mJtuuimjRo3KqFGjcvDgwfTo0SMvvPBCvv3222zbti3nn39+6urqkqTD65+1tramtbX1TzmWtra2lJWVZeDAgdm5c6cfDgBQ5A4AAPiD7r333syePTsHDx5Mkhw8eDBz5szJfffdl5qampx77rlZsWJFxo8fX3x97rnndpjxy0/SW1paMm3atKxcuTJvvvlmhg8fniQ577zzsmjRorzyyitZtWpVBgwY0OnxzJs3Lw8//PBJy7va/t13381FF12UJHn55ZdTW1ubJBk4cGAWL16ccePGZePGjdmwYUMGDx7c5XVoaWnJvHnzsn379tTU1GTRokXZsWNHJkyYkOSnOx0aGhrS1NRUXNa7d+/U1dWloaEhCxcuzJ49e07rXAEAAQAA/jKXXnppPv300w7LPvnkk/Tt2zfLli3L4cOHM3LkyDz//PPF1z/88EOX88rLy7N///7cddddGT9+fPEP8pkzZ6a+vj533313HnroocydO7fT7bdv354kGTRoUIflXW2/ZcuWVFVVpbS0NCUlJenXr1+SpKqqKu+8804mTZqUu+66Kw8++GDuuOOOLo+7srIyy5cvT3V1dWbPnp26urpUV1fn3nvvTZKMHTs2Tz31VO68887issceeyzr1q3LHXfckcbGxmIY+a3nCgD8dh4BAIAzoKSkJMePH/9d25aWlua1115LknzzzTfp0aNHkp8eNbj44ouL7zvnnHNy1llnpVAonDRj3rx5eeSRR7Jjx47isq6237JlS2699da0tLTks88+y5VXXplu3bqlqqoqy5cvz6BBg7JgwYK8+OKLmTx5cpfH3d7enj179qRQKOTYsWPZs2dP2tvbc/bZZydJ5syZk9tuuy233HJLunXrluSnuwymTp2aJGlqaiqey+mcKwAgAADAX6K1tTX9+/fPrl27isv69+//u5/rb2trKz5OkKQYEsrKyjJmzJgcPXo0paWlufbaa7v8g3jnzp0pFAq54YYb/v8f/S6237lzZ6ZPn55rrrkmH374YY4cOZKBAwemsrIy33//faZMmZKqqqqMHz8+I0aMyJQpUzrd57Fjx4rHc/To0bS3t3dYv2TJkjQ2Nqa+vr74pYfl5eUdoklJSclpnysA8Nt4BAAA/qAlS5ZkxowZxf/ar0ePHnn00Ufz3HPP/a55Xd058NFHHxW/D2DIkCGZOHHiKeec+F0AXW1/5MiRfPfdd7n11luza9eufPjhh5kwYULef//9dO/ePStXrkxzc3MmTZqUIUOG/O7rdNVVV2XdunWprKxMZWVlkqS5uTnDhg1LkgwfPrwYAE73XAGAX+cOAAD4g7Zu3ZoLLrggr7/+etra2lJeXp76+vq89957p9zuq6++ysSJE/Pss8/+pv3U1tZm7ty5qampyY8//php06ad8v0ffPBB2traUlFR8avbb9myJaNHj87+/fvz8ccf57rrrsvTTz+dQ4cO5a233sratWtTWlqahQsX/u7r9NJLL2XNmjVpaWnJgQMHUlFRkdra2ixYsCBjx45Nc3NzDh8+/LvOFQD4dSW9evU67jIAAP8N8+fPz9KlS7N3795cffXVefzxx3PnnXe6MABwBrgDAAD4r6mvr88TTzyRI0eOpLy8PDNmzHBRAOAMcQcAAAAA/A/wJYAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAIAA4BIAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAgAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAIAAAAAAAAgAAAAAgAAAAAAACAAAAACAAAAAAAAIAAAAAIAAAAAAAAgAAAAAIAAAAAIAAAAAAAAgAAAAAwN9ZyX+W57jLAAAAAP9u7gAAAAAAAQAAAAAQAAAAAAABAAAAABAAAAAAAAEAAAAAEAAAAAAAAQAAAAAQAAAAAOB/yv8B7WVONQum3vwAAAAASUVORK5CYII=");

    public static IEndpointRouteBuilder MapNewsEndpoints(this IEndpointRouteBuilder app)
    {
        var configured = app.ServiceProvider
            .GetRequiredService<IOptions<BreakerOptions>>()
            .Value;

        if (!Uri.TryCreate(configured.NewsImageUrl, UriKind.Absolute, out var imageUri))
            throw new InvalidOperationException("Breaker:NewsImageUrl must be an absolute URL.");

        var imageRoute = imageUri.AbsolutePath;

        app.MapMethods(imageRoute, [HttpMethods.Get, HttpMethods.Head], (
            IWebHostEnvironment environment,
            IOptions<BreakerOptions> options) =>
        {
            var file = FindNewsImage(environment, options.Value.NewsImageFile);

            if (file is not null)
                return Results.File(file, "image/png");

            // Never return 404 for the news image. The client treats a failed
            // image request as a fatal game-server communication error.
            return Results.File(FallbackNewsImage, "image/png");
        });

        var api = app.MapGroup("/dbtb-prd/{title}/api");

        api.MapPost("/news/get_3d_model_news", (
            ApiResponseService responses,
            IOptions<BreakerOptions> options) =>
        {
            var (availableAt, expireAt) = ActiveWindow();
            return responses.Respond(new object?[]
            {
                0,
                new object?[]
                {
                    new object?[]
                    {
                        options.Value.NewsImageUrl,
                        availableAt,
                        expireAt
                    }
                }
            });
        });

        api.MapPost("/news/get_2d_ui_news_list", (ApiResponseService responses) =>
            responses.Respond(new object?[]
            {
                0,
                Array.Empty<object?>()
            }));

        return app;
    }

    private static (string AvailableAt, string ExpireAt) ActiveWindow()
    {
        var now = DateTimeOffset.Now;
        return (
            now.AddDays(-1).ToString("yyyy-MM-dd HH:mm:ss"),
            now.AddYears(10).ToString("yyyy-MM-dd HH:mm:ss"));
    }

    private static string? FindNewsImage(IWebHostEnvironment environment, string configuredPath)
    {
        if (string.IsNullOrWhiteSpace(configuredPath))
            return null;

        if (Path.IsPathRooted(configuredPath))
            return File.Exists(configuredPath) ? configuredPath : null;

        var candidates = new[]
        {
            Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, configuredPath)),
            Path.GetFullPath(Path.Combine(environment.ContentRootPath, configuredPath)),
            Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), configuredPath))
        };

        return candidates.FirstOrDefault(File.Exists);
    }
}
